In [0]:
# Numpy - Data Science Library
import numpy as np

# array()

In [9]:

# 2D Array
twoD=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# 2X3 MARIX
twod=np.array([[1,2],[2,3],[3,4]])
print(twod)

[[1 2]
 [2 3]
 [3 4]]


In [12]:
print(twoD.shape)

(3, 3)


In [17]:
# Loop to print the Content of the array

for items in arr:
  print(items)

0.0
0.0
0.0
0.0


In [16]:
for index in range(len(arr)):      # Range(5)=0,1,2,3,4
  print('index ',index,':',arr[index])

index  0 : 0.0
index  1 : 0.0
index  2 : 0.0
index  3 : 0.0


In [18]:
# Numpy InBulit Methods

# (1.) zeros()
# used to fill an array with 0's

#1D

arr=np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [20]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# (2.) ones()
# used to fill an array with 1's

arr=np.ones((4,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
# (3.) full()
# used to fill an array with a constant value

arr=np.full((3,3),121)
print(arr)

[[121 121 121]
 [121 121 121]
 [121 121 121]]


In [25]:
# (4.) random()
# used to fill an array with random values

arr=np.random.random((4,2))
# fill an array starting with zero (0) till one (1)
print(arr)

[[0.83551803 0.12481433]
 [0.77811138 0.90299886]
 [0.27801545 0.38541851]
 [0.46772877 0.89869358]]


In [28]:
# (5.) used to generate integer values

arr=np.random.randint(5,20,size=(4,2))
print(arr)

[[ 7  9]
 [16 13]
 [12 11]
 [ 9 15]]


In [31]:
# (6.) identity()
# used to fill diagonal of an array with 1
# used only for MultiDimentional arrays
arr=np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
# Datatypes in numpy
# (7.) astype()
# used to change the dataType of an array

newArr= arr.astype(int)
print(newArr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [34]:
intArray=np.array([1,2,3,4,5])
floatArray=np.array([1.,2.,3.,4.,5.])
charArray=np.array(['a','b','c','d','e'])
print(intArray.dtype)
print(floatArray.dtype)
print(charArray.dtype)

int64
float64
<U1


In [35]:
intArray=np.array([1,2,3,4,5],dtype=np.float32)
print(intArray)

[1. 2. 3. 4. 5.]


In [37]:
arr=np.zeros(6,dtype=int)
print(arr)

[0 0 0 0 0 0]


In [47]:
# (8.) arange(x)
# used to generate the sequence of Integer Values
# Starting from 0 till x-1

print(np.arange(11))

# (9.) arange(x,y)
# used to generate sequence of integer values
# Starting from x till y-1

print(np.arange(1,11))

# (10.) arange(x,y,StepCount)
# used to generate sequence of integer values
# Starting from x till y-1 with the differnce of the stepcount value

print(np.arange(0,21,2))

x=np.arange((21),dtype=np.float)
x

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [50]:
# (11.) Linspace()
# used to print evenly interval values

print(np.linspace(1,50,num=4))


[ 1. 18. 35. 52.]


In [52]:
# in linspace bydefalut num=50
print(np.linspace(0,1))


[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [56]:
# (12.) reshape()
# used to reshape the dimensions of your array

# Convert 1D to 2D

arr=np.array([10,20,30,40,50,60])
twoD=arr.reshape(3,2)
print(twoD)

[[10 20]
 [30 40]
 [50 60]]


In [57]:
# Convert 2D to 1D

twoD=np.array([[1,2,3],[4,5,6],[7,8,9]])
oneD=twoD.reshape(9)
print(oneD)

[1 2 3 4 5 6 7 8 9]


In [60]:
# Convert 1D to 2D using arange()
arr =np.arange(10).reshape(5,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [62]:
print(arr.transpose())

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [64]:
# Numpy Broadcasting
# https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
# arrays having same size and shape can undergo arithmetic operations
a=np.array([3,4,5])
b=np.array([2,3,4])
a*b

array([ 6, 12, 20])

In [65]:
# arrays having size one with 1 can also undergo arithmetic operations

a=np.array([3,4,5])
b=np.array([2])
a*b

array([ 6,  8, 10])

In [66]:
# additions between two arrays

arr=np.array([[0,0,0],[10,10,10],[20,20,20],
             [30,30,30]])
x=np.array([0,1,2])
print(arr+x)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
